FORMAT: 1A
HOST: https://obelisk.ilabt.imec.be/api

# Obelisk

Welcome to the developer documentation for Obelisk.

1. Make yourself known to the platform by logging in at https://obelisk.ilabt.imec.be
2. Ensure you have access to the datasets you will be working with [TODO: link to help article on requesting access]
3. (Optional) Create the necessary clients beforehand [TODO]

# Group Authentication

# Group Catalog API

## Catalog GraphQL [/catalog/graphql]

### Run Query [POST]

+ Request Execute GraphQL Query (application/json)
    + Attributes (GraphQLRequest)

+ Response 200 (application/json)

        {
          "data": {
            "me": {
              "id": "U1581692393568",
              "email": "user1@oblx.io"
            }
          }
        }
            
# Group Data API
            
## Data Ingest [/data/ingest/{datasetId}]

### Ingest [POST]

+ Request Ingest Primitive data (application/json)

+ Response 204

+ Request Ingest JSON data (application/json)

+ Response 204

+ Response 400

## Data Querying [/data/query]

### Query Raw Events [POST /events]

+ Response 200 (application/json)

### Query Latest Events [POST /events/latest]

+ Response 200 (application/json)

### Query Statistics [POST /stats]

+ Response 200 (application/json)

## Data Streaming [/data/streams/{streamId}]

### Server-Sent-Events [GET]

+ Response 200 (application/json)

## Data Export [/data/exports/{exportId}]

### Download Batch [GET]

+ Response 200 (application/json)

# Data Structures

## GraphQLRequest (object)

+ query (string)
+ operationName (string)
+ variables (object)